default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: iregremlin_development

test:
  <<: *default
  database: iregremlin_test
  username: travis
  password: ""
  host: 127.0.0.1

production:
  <<: *default
  database: iregremlin_production
  username: iregremlin
  password: <%= ENV['HAARSHOUSE_DATABASE_PASSWORD'] %>
